export const userIfExist = "api/v1/Auth/emailexists?phone=";
export const getOtp = "/api/v1/Auth/RequestOTP";
export const verifyOtp = "/api/v1/Auth/Register";
export const login = "/api/v1/Auth/Login";
export const addressDivisions = "/api/v1/Provinces";
export const addressDistrict = "/api/v1/Districts/ByProvince/";
export const addressArea = "/api/v1/Upazilas/ByDistrict/";
export const banners = "/api/v1/Banners?bannerType=";
export const getProfileInfo = "/api/v1/Customers";
export const updateProfileInfo = "/api/v1/Customers";
export const postComplain = "/api/v1/Complains";
export const postAddress = "/api/v1/Addresses";
export const GET_ADDRESS = "/api/v1/Addresses";
export const GET_PROMOTIONAL = "/api/v1/Promotions";
export const POST_ORDER_PAYMENT = "/api/v1/Orders/PaymentInfo";
export const POST_ORDER = "/api/v1/Orders";
export const GET_ORDERS = "/api/v1/Orders";
export const GET_ORDER_DETAILS = "/api/v1/Orders/";
export const GET_SUBCATEGORY_PRODUCTS =
  "/api/v1/Categories/ChildrenWithProducts/";
export const GET_PRODUCT_DETAILS = "/api/v1/Products/";
